#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Wed Mar 29 15:53:12 2023

add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/hdmi_ddr_ov5640_top.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/cmos_8_16bit.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/fram_buf.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/i2c_com.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/iic_dri.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/ms72xx_ctl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/ms7200_ctl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/ms7210_ctl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/power_on_delay.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/rd_buf.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/rd_ctrl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/reg_config.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/sync_vg.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_buf.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_cmd_trans.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_ctrl.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_rd_ctrl_top.v"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/pll/pll.idf"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/wr_fram_buf/wr_fram_buf.idf"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/rd_fram_buf/rd_fram_buf.idf"
add_design "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/source/rtl/DDR3_50H/DDR3_50H.idf"
add_constraint "C:/Users/w/Desktop/HDMI_DDR3_OV5647_test/hdmi_ddr_ov5640_top.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_hdmi/cmos_write_req_gen.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_hdmi/color_bar.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_hdmi/video_define.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_hdmi/video_timing_data.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_ddr3/aq_axi_master_256.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_ddr3/frame_fifo_read.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_ddr3/frame_fifo_write.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_ddr3/frame_read_write.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
add_design D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/ipcore/afifo_16i_64o_512/afifo_16i_64o_512.idf
add_design D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/ipcore/afifo_64i_16o_128/afifo_64i_16o_128.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_hdmi/video_rect_read_data.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_ddr_2.0/source/frame_hdmi/timing_gen_xy.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module cmos_8_16bit
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/frame_ddr3/mem_read_arbi.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/frame_ddr3/mem_write_arbi.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/helai_video_scale/helai_video_scale.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/helai_video_scale/ramDualPort.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/helai_video_scale/ramFifo.v"
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/fifo_generator_0/fifo_generator_0.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/spf/video_packet_rec.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/spf/video_packet_send.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/spf/word_align.v"
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/fifo_4096_16i_32o/fifo_4096_16i_32o.idf
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/fifo_2048_32i_16o/fifo_2048_32i_16o.idf
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/hsst_core/hsst_core.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/fram_buf.v"
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/rd_buf.v"
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/wr_buf.v"
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/wr_rd_ctrl_top.v"
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/wr_cmd_trans.v"
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/wr_ctrl.v"
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/rd_ctrl.v"
remove_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/wr_fram_buf/wr_fram_buf.idf
remove_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/rtl/rd_fram_buf/rd_fram_buf.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/tx/arp_tx.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/tx/ip_tx.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/tx/ip_tx_mode.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/tx/mac_tx.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/tx/mac_tx_mode.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/tx/mac_tx_top.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/tx/udp_tx.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/imports/src/util_gmii_to_rgmii.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/debouce/ax_debounce.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/mac/arp_cache.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/mac/icmp_reply.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/mac/mac_test.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/mac/mac_top.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/rtl/crc.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/rx/arp_rx.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/rx/ip_rx.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/rx/mac_rx.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/rx/mac_rx_top.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/rx/udp_rx.v"
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/pll_sft/pll_sft.idf
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/frame_hdmi/video_timing_data.v"
remove_design -verilog "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/frame_hdmi/color_bar.v"
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/udp_rx_ram_8_2048/udp_rx_ram_8_2048.idf
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/udp_tx_data_fifo/udp_tx_data_fifo.idf
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/uudp_checksum_fifo_drm/uudp_checksum_fifo_drm.idf
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/eth_rx_process.v"
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/eth/reset_dly.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
add_design "D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/source/frame_hdmi/color_bar.v"
remove_design -force D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/uudp_checksum_fifo_drm/uudp_checksum_fifo_drm.idf
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/udp_checksum_fifo_drm/udp_checksum_fifo_drm.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/icmp_rx_ram_8_256/icmp_rx_ram_8_256.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
remove_design -force D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/icmp_rx_ram_8_256/icmp_rx_ram_8_256.idf
add_design D:/pds/PDS_2022.1/prj/final_ov_hdmi_ddr/ipcore/icmp_rx_ram_8_256/icmp_rx_ram_8_256.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
add_design "D:/pds2022_1/base_bord/pg_base/source/video_scale_down.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
add_fic "D:/pds_2022_1/prj/pg_base_1080P_sfp/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
remove_fic "D:/pds_2022_1/prj/pg_base_1080P_sfp/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
add_fic "D:/pds_2022_1/prj/pg_base_1080P_sfp/synthesize/hdmi_ddr_ov5640_top_syn.fic"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/helai_video_scale/helai_video_scale.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/helai_video_scale/ramFifo.v"
remove_design D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/ipcore/fifo_generator_0/fifo_generator_0.idf
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/mac/mac_top.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/debouce/ax_debounce.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/helai_video_scale/ramDualPort.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/mac/mac_test.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/reset_dly.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/imports/src/util_gmii_to_rgmii.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/video_scale_down.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/mac/icmp_reply.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/rx/mac_rx_top.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/tx/mac_tx_top.v"
remove_design D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/ipcore/pll_sft/pll_sft.idf
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/mac/arp_cache.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/rx/arp_rx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/tx/arp_tx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/rtl/crc.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/rx/ip_rx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/tx/ip_tx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/tx/ip_tx_mode.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/rx/mac_rx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/tx/mac_tx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/tx/udp_tx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/rx/udp_rx.v"
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/tx/mac_tx_mode.v"
remove_design D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/ipcore/icmp_rx_ram_8_256/icmp_rx_ram_8_256.idf
remove_design -verilog "D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/source/eth/eth_rx_process.v"
remove_design D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/ipcore/udp_rx_ram_8_2048/udp_rx_ram_8_2048.idf
remove_design D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/ipcore/udp_tx_data_fifo/udp_tx_data_fifo.idf
remove_design D:/xy/pg_base_1080P_sfp/pg_base_1080P_sfp/ipcore/udp_checksum_fifo_drm/udp_checksum_fifo_drm.idf
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
add_design "D:/pds_2022_1/sfp_1080p/pg_base_1080P_sfp/source/video_scale_down.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {40M} 
